# Generated by Django 5.0.14 on 2025-12-10 06:38

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='首頁大標題')),
                ('hero_subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='首頁副標題')),
                ('trust_indicators', wagtail.fields.StreamField([('benefit', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='優勢標題')), ('description', wagtail.blocks.TextBlock(label='優勢說明')), ('icon_class', wagtail.blocks.CharBlock(label='圖示代碼 (如 fa-shield)', required=False))], label='信任指標'))], blank=True, null=True, verbose_name='信任指標區塊')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='首頁背景圖')),
            ],
            options={
                'verbose_name': '首頁',
            },
            bases=('wagtailcore.page',),
        ),
    ]
