# Generated by Django 5.0.14 on 2025-12-12 12:55

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(blank=True, max_length=250, verbose_name='頁面簡介')),
                ('body', wagtail.fields.RichTextField(verbose_name='頁面內容')),
            ],
            options={
                'verbose_name': '通用頁面 (標準)',
            },
            bases=('wagtailcore.page',),
        ),
    ]
