# Generated by Django 5.0.14 on 2025-12-10 06:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': '學術研究列表頁',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResearchPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('publication_date', models.DateField(verbose_name='發表/公告日期')),
                ('institution', models.CharField(max_length=255, verbose_name='研究機構/作者')),
                ('category', models.CharField(choices=[('SCI', 'SCI 期刊論文'), ('CLINICAL', '人體臨床實驗'), ('PATENT', '發明專利'), ('REPORT', '檢驗報告')], default='SCI', max_length=50, verbose_name='資料類別')),
                ('summary', wagtail.fields.RichTextField(verbose_name='研究摘要')),
                ('pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document', verbose_name='完整文件/證書 (PDF)')),
            ],
            options={
                'verbose_name': '研究文獻/專利',
            },
            bases=('wagtailcore.page',),
        ),
    ]
