# Generated by Django 5.0.14 on 2025-12-10 06:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': '產品列表頁',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('product_type', models.CharField(choices=[('B2C', '終端產品 (B2C)'), ('B2B', '保健原料 (B2B)')], default='B2C', max_length=20, verbose_name='產品類型')),
                ('short_description', models.TextField(blank=True, verbose_name='簡短描述')),
                ('triterpenoids', models.CharField(blank=True, max_length=50, verbose_name='三萜類含量 (如 12%)')),
                ('polysaccharides', models.CharField(blank=True, max_length=50, verbose_name='多醣體含量 (如 >5%)')),
                ('full_description', wagtail.fields.RichTextField(verbose_name='完整產品介紹')),
                ('usage_instructions', wagtail.fields.RichTextField(blank=True, verbose_name='使用建議')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='產品主圖')),
            ],
            options={
                'verbose_name': '產品頁面',
            },
            bases=('wagtailcore.page',),
        ),
    ]
